-- MySQL Script generated by MySQL Workbench
-- 07/10/16 10:49:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yushin_gwt_test_project_for_rozdoum_db2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yushin_gwt_test_project_for_rozdoum_db2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yushin_gwt_test_project_for_rozdoum_db2` DEFAULT CHARACTER SET utf8 ;
USE `yushin_gwt_test_project_for_rozdoum_db2` ;

-- -----------------------------------------------------
-- Table `yushin_gwt_test_project_for_rozdoum_db2`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yushin_gwt_test_project_for_rozdoum_db2`.`clients` (
  `id` INT NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `surname` VARCHAR(25) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `dataOfBirth` VARCHAR(15) NOT NULL,
  `sex` VARCHAR(10) NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
